//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatPhong()
        {
            this.ChiTietDonDats = new HashSet<ChiTietDonDat>();
        }
    
        public int id_DDP { get; set; }
        public int id_KH { get; set; }
        public System.DateTime ngaydat_DDP { get; set; }
        public int trangthai_DDP { get; set; }
        public Nullable<int> loaidatcoc_NT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDat> ChiTietDonDats { get; set; }
    }
}
