//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int id_HA { get; set; }
        public string url_HA { get; set; }
        public int id_NT { get; set; }
    
        public virtual NhaTro NhaTro { get; set; }
    }
}
