//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaTro()
        {
            this.HinhAnhs = new HashSet<HinhAnh>();
            this.Phongs = new HashSet<Phong>();
        }
    
        public int id_NT { get; set; }
        public string ten_NT { get; set; }
        public string CCCD_NT { get; set; }
        public string diachi_NT { get; set; }
        public string email_NT { get; set; }
        public Nullable<int> sophong_NT { get; set; }
        public string sodt_NT { get; set; }
        public string ghichu_NT { get; set; }
        public string userName { get; set; }
        public double dienTich_NT { get; set; }
        public int gac_NT { get; set; }
        public double gia_NT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
