//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.ChiTietDonDats = new HashSet<ChiTietDonDat>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int id_P { get; set; }
        public Nullable<int> songuoi_P { get; set; }
        public string noithat_P { get; set; }
        public Nullable<int> trangthai_P { get; set; }
        public string dientich_P { get; set; }
        public Nullable<int> gac_P { get; set; }
        public string ghichu_P { get; set; }
        public int id_NT { get; set; }
        public string ten_P { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDat> ChiTietDonDats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual NhaTro NhaTro { get; set; }
    }
}
